# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4995cae6-83fc-465b-b86a-2d37e81b4734";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BD4A-0843";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/d24b066d-90b0-4e0d-b410-8d852e2f1327";
      fsType = "ext4";
    };

  fileSystems."/home/narice/ssd" =
    { device = "/dev/disk/by-uuid/3c41d6fb-3268-49f9-bb4c-f113c5eb7afc";
      fsType = "ext4";
    };

  fileSystems."/home/narice/hdd" =
    { device = "/dev/disk/by-uuid/aef4e457-bfed-41b9-bb68-291f7fb7da77";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/eccf866b-ea3c-4b89-91c8-9e2368df37e7"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
